name = "quantumSim"
uuid = "281df352-8c17-4805-9961-d9a149125cad"
authors = ["Dohyun Kim"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
